version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.11.8"  # Ensure this matches your Python version

python:
  install:
    - requirements: requirements-docs.txt  # Use the requirements file specific to documentation

mkdocs:
  configuration: docs/mkdocs.yml  # Point to your MkDocs configuration file inside the docs directory

