version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.11"  # Use the version you are working with (adjust if needed)

python:
  install:
    - requirements: requirements.txt  # Ensure this file contains MkDocs and its dependencies

mkdocs:
  configuration: docs/mkdocs.yml  # Point to your MkDocs configuration file inside the docs directory

