version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.11"  # Ensure this matches your Python version

python:
  install:
    - requirements: requirements-docs.txt  # Use the requirements file specific to documentation

mkdocs:
  configuration: configuration: mkdocs.yml  # Path is now in the root directory