# Transfer script - allows interactive password input
# Template: replace <LOCAL_DIR>, <SSH_USER>, <SSH_HOST>, <REMOTE_DIR>, <SSH_PORT>
# Generated by vaila's SSH Transfer feature; do not commit personal values.
Write-Host "============================================" -ForegroundColor Cyan
Write-Host "File Transfer (RSYNC)" -ForegroundColor Cyan
Write-Host "============================================" -ForegroundColor Cyan
Write-Host ""
Write-Host "Transferring: <LOCAL_DIR>" -ForegroundColor Yellow
Write-Host "To: <SSH_USER>@<SSH_HOST>:<REMOTE_DIR>" -ForegroundColor Yellow
Write-Host "SSH Port: <SSH_PORT>" -ForegroundColor Yellow
Write-Host ""
Write-Host "You will be prompted for your SSH password." -ForegroundColor Green
Write-Host "Enter your password when prompted (it will not be visible)." -ForegroundColor Green
Write-Host ""
Write-Host "Starting transfer..." -ForegroundColor Cyan
Write-Host ""

# Execute the command with proper argument handling
$cmdArgs = @(
    "-avhP",
    "-e",
    "ssh -p <SSH_PORT>",
    "<LOCAL_DIR>/",
    "<SSH_USER>@<SSH_HOST>:<REMOTE_DIR>/"
)
& "C:\\ProgramData\\chocolatey\\bin\\rsync.EXE" $cmdArgs

if ($LASTEXITCODE -eq 0) {
    Write-Host ""
    Write-Host "[OK] Transfer completed successfully!" -ForegroundColor Green
} else {
    Write-Host ""
    Write-Host "[FAIL] Transfer failed! (Exit code: $LASTEXITCODE)" -ForegroundColor Red
    Write-Host "Please check your connection and credentials." -ForegroundColor Yellow
}

Write-Host ""
Write-Host "Press any key to close this window..." -ForegroundColor Gray
$null = $Host.UI.RawUI.ReadKey("NoEcho,IncludeKeyDown")
