"""
Project: vailá Multimodal Toolbox
Script: yolotrain.py - vailá YOLO26 Trainer

Author: Paulo Roberto Pereira Santiago
Email: paulosantiago@usp.br
GitHub: https://github.com/vaila-multimodaltoolbox/vaila
Creation Date: 24 May 2025
Update Date: 23 June 2026
Version: 0.3.56

Description:
    YOLO26-first training interface for datasets generated by vailá/getpixelvideo,
    vailá/vaila_sam, and existing Ultralytics YOLO-format datasets.

Usage:
    Run the script from the command line:
        python yolotrain.py
        python -m vaila.yolotrain --data /path/to/data.yaml --task auto --model auto

Requirements:
    - Python 3.x
    - Ultralytics YOLO
    - Tkinter (for GUI operations)

License:
    This project is licensed under the terms of GNU General Public License v3.0.

Change History:
    - v0.3.56: Removed legacy external-labeler flow, added YOLO task auto-detection
               (detect/pose/segment), YOLO26 defaults, GUI training controls,
               and headless CLI training from data.yaml.
    - v0.3.53: Dataset build now runs in a worker thread with sequential video
               decode (no more shuffled cap.set seeks that froze the GUI on
               large CSVs); train/val splits no longer duplicate a train row
               into val; _resolve_yaml_path uses removeprefix("./") so
               "../images/train" and list-valued train/val entries resolve
               correctly.
    - v0.3.51: Added getpixelvideo/sam_points_georeid CSV to YOLO tracking dataset builder
    - v0.0.4: Simplified interface, legacy labeler-focused YAML generation
    - v0.0.3: Added support for legacy external labeler data, improved UI
    - v0.0.2: Added validation and threading support
    - v0.0.1: First version
"""

import argparse
import contextlib
import os
import pathlib
import random
import sys
import threading
import tkinter as tk
from dataclasses import dataclass
from datetime import datetime
from tkinter import filedialog, messagebox, scrolledtext, simpledialog, ttk

import cv2
import pandas as pd
import torch
from ultralytics import YOLO

# import datetime
# import re
# import webbrowser


IMAGE_EXTENSIONS = (".jpg", ".jpeg", ".png", ".bmp", ".tif", ".tiff", ".webp")
TASK_CHOICES = ("auto", "detect", "pose", "segment")
AUTO_MODEL_LABEL = "auto (YOLO26 by dataset task)"

DEFAULT_MODEL_BY_TASK = {
    "detect": "yolo26m.pt",
    "pose": "yolo26m-pose.pt",
    "segment": "yolo26m-seg.pt",
}

YOLO26_MODELS = [
    "yolo26n.pt",
    "yolo26s.pt",
    "yolo26m.pt",
    "yolo26l.pt",
    "yolo26x.pt",
    "yolo26n-pose.pt",
    "yolo26s-pose.pt",
    "yolo26m-pose.pt",
    "yolo26l-pose.pt",
    "yolo26x-pose.pt",
    "yolo26n-seg.pt",
    "yolo26s-seg.pt",
    "yolo26m-seg.pt",
    "yolo26l-seg.pt",
    "yolo26x-seg.pt",
]


@dataclass(frozen=True)
class TrainingConfig:
    """Resolved YOLO training configuration shared by GUI and CLI."""

    yaml_file: str
    dataset_dir: str
    train_path: str
    val_path: str
    task: str
    model_name: str
    epochs: int
    batch: int | float
    imgsz: int
    device: str
    project: str
    name: str


def _load_yaml(yaml_file):
    """Load a YOLO data.yaml file."""
    import yaml

    with open(yaml_file, encoding="utf-8") as f:
        data = yaml.safe_load(f) or {}
    if not isinstance(data, dict):
        raise ValueError(f"Invalid YAML mapping: {yaml_file}")
    return data


def _yaml_names_to_list(names):
    """Normalize Ultralytics ``names`` list/dict/string to a list of class names."""
    if isinstance(names, dict):
        out = []
        for key in sorted(names, key=lambda value: int(value) if str(value).isdigit() else value):
            value = str(names[key]).strip()
            if value:
                out.append(value)
        return out
    if isinstance(names, (list, tuple)):
        return [str(item).strip() for item in names if str(item).strip()]
    if isinstance(names, str):
        text = names.strip()
        return [text] if text else []
    return []


def _read_classes_txt(dataset_path):
    classes_file = os.path.join(dataset_path, "classes.txt")
    if not os.path.exists(classes_file):
        return []
    try:
        with open(classes_file, encoding="utf-8") as f:
            return [line.strip() for line in f if line.strip()]
    except OSError:
        return []


def _default_device():
    """Prefer CUDA/MPS when available; otherwise use CPU."""
    if torch.cuda.is_available():
        return "0"
    mps = getattr(getattr(torch, "backends", None), "mps", None)
    if mps is not None:
        with contextlib.suppress(Exception):
            if mps.is_available():
                return "mps"
    return "cpu"


def _resolve_yaml_path_entry(yaml_data, dataset_dir, key):
    """Resolve an Ultralytics train/val/test path entry."""
    raw = yaml_data.get(key, "")
    if isinstance(raw, (list, tuple)):
        for item in raw:
            value = str(item).strip()
            if value:
                break
        else:
            value = ""
    else:
        value = str(raw).strip()
    if not value:
        return value
    if os.path.isabs(value):
        return value
    base = str(yaml_data.get("path") or dataset_dir).strip() or dataset_dir
    if not os.path.isabs(base):
        base = os.path.join(dataset_dir, base)
    return os.path.normpath(os.path.join(base, value.removeprefix("./")))


def _image_count(path):
    if not path or not os.path.isdir(path):
        return 0
    return len([name for name in os.listdir(path) if name.lower().endswith(IMAGE_EXTENSIONS)])


def _label_dir_for_images(image_dir):
    path = pathlib.Path(image_dir)
    if path.name == "images":
        return path.parent / "labels"
    if path.parent.name == "images":
        return path.parent.parent / "labels" / path.name
    return path.parent / "labels"


def _first_label_line(yaml_data, dataset_dir):
    """Return first non-empty label line from train/val labels, if any."""
    for split in ("train", "val"):
        image_dir = _resolve_yaml_path_entry(yaml_data, dataset_dir, split)
        label_dir = _label_dir_for_images(image_dir)
        if not label_dir.is_dir():
            continue
        for txt_path in sorted(label_dir.glob("*.txt")):
            with contextlib.suppress(OSError), open(txt_path, encoding="utf-8") as f:
                for line in f:
                    line = line.strip()
                    if line:
                        return line
    return ""


def _model_task(model_name):
    stem = pathlib.Path(str(model_name)).name.lower()
    if "-pose" in stem:
        return "pose"
    if "-seg" in stem:
        return "segment"
    return "detect"


def _looks_like_named_yolo_model(model_name):
    """Return True for named Ultralytics family weights where suffix implies task."""
    stem = pathlib.Path(str(model_name)).name.lower()
    return stem.startswith(("yolo", "yolov")) and stem.endswith(".pt")


def _suggest_model_for_task(dataset_task, model_name):
    """Suggest same-family YOLO model suffix for the dataset task when possible."""
    name = pathlib.Path(str(model_name)).name
    lower = name.lower()
    if lower.endswith(".pt") and _looks_like_named_yolo_model(name):
        base = name[:-3]
        for suffix in ("-pose", "-seg"):
            if base.lower().endswith(suffix):
                base = base[: -len(suffix)]
                break
        if dataset_task == "pose":
            return f"{base}-pose.pt"
        if dataset_task == "segment":
            return f"{base}-seg.pt"
        return f"{base}.pt"
    return DEFAULT_MODEL_BY_TASK.get(dataset_task, DEFAULT_MODEL_BY_TASK["detect"])


def _validate_model_task_match(dataset_task, model_name):
    """Fail early when a known YOLO model family does not match the dataset task."""
    model_task = _model_task(model_name)
    if dataset_task == model_task or not _looks_like_named_yolo_model(model_name):
        return

    expected = _suggest_model_for_task(dataset_task, model_name)
    if dataset_task == "pose":
        detail = (
            "This dataset has kpt_shape / YOLO-pose labels. A detect model will read "
            "keypoint visibility values (2) as coordinates and Ultralytics will report "
            "'non-normalized or out of bounds coordinates [2. 2.]'."
        )
    elif dataset_task == "segment":
        detail = "This dataset appears to contain polygon labels and needs a *-seg.pt model."
    else:
        detail = "This dataset contains bbox detection labels and needs a detection model."
    raise ValueError(
        f"Model/task mismatch: dataset task is '{dataset_task}' but model '{model_name}' "
        f"is a '{model_task}' model. Use --model {expected} or --model auto. {detail}"
    )


def _detect_task_from_yaml(yaml_data, dataset_dir):
    """Detect Ultralytics task from data.yaml and label shape."""
    yaml_task = str(yaml_data.get("task", "")).strip().lower()
    if yaml_task in {"detect", "pose", "segment"}:
        return yaml_task

    model_name = str(yaml_data.get("model", "")).strip()
    if model_name:
        model_task = _model_task(model_name)
        if model_task != "detect":
            return model_task

    if "kpt_shape" in yaml_data:
        return "pose"

    label_line = _first_label_line(yaml_data, dataset_dir)
    if label_line:
        parts = label_line.split()
        if len(parts) > 5:
            return "segment"
    return "detect"


def _select_model_name(yaml_data, task, requested_model):
    """Choose model with YOLO26 defaults when GUI/CLI is set to auto."""
    requested = str(requested_model or "").strip()
    if requested and requested.lower() not in {"auto", AUTO_MODEL_LABEL.lower()}:
        return requested

    yaml_model = str(yaml_data.get("model", "")).strip()
    if yaml_model and _model_task(yaml_model) == task:
        return yaml_model
    return DEFAULT_MODEL_BY_TASK.get(task, DEFAULT_MODEL_BY_TASK["detect"])


def _coerce_int(value, default):
    try:
        return int(value)
    except (TypeError, ValueError):
        return int(default)


def _coerce_batch(value, default):
    try:
        numeric = float(value)
    except (TypeError, ValueError):
        return default
    return int(numeric) if numeric.is_integer() else numeric


def _resolve_training_config(
    yaml_file,
    *,
    task="auto",
    model="auto",
    epochs=None,
    batch=None,
    imgsz=None,
    device=None,
    project=None,
    name="yolo_training",
):
    """Resolve, validate, and normalize GUI/CLI training settings."""
    yaml_file = os.path.abspath(str(yaml_file))
    if not os.path.exists(yaml_file):
        raise FileNotFoundError(f"YAML file not found: {yaml_file}")

    yaml_data = _load_yaml(yaml_file)
    dataset_dir = os.path.dirname(yaml_file)
    missing = [field for field in ("train", "val", "names") if field not in yaml_data]
    if missing:
        raise ValueError(f"Missing required YAML fields: {missing}")

    requested_task = str(task or "auto").strip().lower()
    if requested_task not in TASK_CHOICES:
        raise ValueError(f"Invalid task '{task}'. Use one of: {', '.join(TASK_CHOICES)}")
    resolved_task = (
        _detect_task_from_yaml(yaml_data, dataset_dir)
        if requested_task == "auto"
        else requested_task
    )

    model_name = _select_model_name(yaml_data, resolved_task, model)
    _validate_model_task_match(resolved_task, model_name)
    train_path = _resolve_yaml_path_entry(yaml_data, dataset_dir, "train")
    val_path = _resolve_yaml_path_entry(yaml_data, dataset_dir, "val")
    if not os.path.exists(train_path):
        raise FileNotFoundError(f"Train images not found: {train_path}")
    if not os.path.exists(val_path):
        raise FileNotFoundError(f"Val images not found: {val_path}")

    resolved_epochs = _coerce_int(
        epochs if epochs is not None else yaml_data.get("epochs", 100), 100
    )
    resolved_batch = _coerce_batch(batch if batch is not None else yaml_data.get("batch", 16), 16)
    resolved_imgsz = _coerce_int(imgsz if imgsz is not None else yaml_data.get("imgsz", 640), 640)

    if device is None:
        resolved_device = str(yaml_data.get("device") or _default_device())
    else:
        device_text = str(device).strip()
        resolved_device = _default_device() if device_text.lower() == "auto" else device_text

    dataset_base = str(yaml_data.get("path") or dataset_dir).strip() or dataset_dir
    if not os.path.isabs(dataset_base):
        dataset_base = os.path.join(dataset_dir, dataset_base)
    dataset_root = os.path.abspath(os.path.normpath(dataset_base))
    resolved_project = os.path.abspath(str(project or os.path.join(dataset_root, "runs")))
    resolved_name = str(name or yaml_data.get("name") or "yolo_training").strip() or "yolo_training"

    return TrainingConfig(
        yaml_file=yaml_file,
        dataset_dir=dataset_root,
        train_path=train_path,
        val_path=val_path,
        task=resolved_task,
        model_name=model_name,
        epochs=resolved_epochs,
        batch=resolved_batch,
        imgsz=resolved_imgsz,
        device=resolved_device,
        project=resolved_project,
        name=resolved_name,
    )


def _model_path_for_training(model_name):
    """Return local model path, downloading named Ultralytics weights into vaila/models if needed."""
    model_text = os.path.expanduser(str(model_name).strip())
    if not model_text:
        raise ValueError("Empty YOLO model name.")
    if os.path.isabs(model_text) or os.sep in model_text:
        return model_text

    models_dir = os.path.join(os.path.dirname(__file__), "models")
    os.makedirs(models_dir, exist_ok=True)
    local_path = os.path.join(models_dir, model_text)
    if os.path.exists(local_path):
        return local_path

    current_dir = os.getcwd()
    try:
        os.chdir(models_dir)
        YOLO(model_text)
    finally:
        os.chdir(current_dir)
    return local_path if os.path.exists(local_path) else model_text


def _parse_extra_train_args(extra_items):
    """Parse ``--arg key=value`` values for Ultralytics train overrides."""
    parsed = {}
    for item in extra_items or []:
        if "=" not in item:
            raise ValueError(f"Extra train argument must be key=value, got: {item}")
        key, value = item.split("=", 1)
        key = key.strip()
        value = value.strip()
        if not key:
            raise ValueError(f"Empty train argument key in: {item}")
        lower = value.lower()
        if lower in {"true", "false"}:
            parsed[key] = lower == "true"
            continue
        if lower in {"none", "null"}:
            parsed[key] = None
            continue
        with contextlib.suppress(ValueError):
            parsed[key] = int(value)
            continue
        with contextlib.suppress(ValueError):
            parsed[key] = float(value)
            continue
        parsed[key] = value
    return parsed


def train_yolo_dataset(
    yaml_file,
    *,
    task="auto",
    model="auto",
    epochs=None,
    batch=None,
    imgsz=None,
    device=None,
    project=None,
    name="yolo_training",
    exist_ok=True,
    dry_run=False,
    extra_train_args=None,
):
    """Train an Ultralytics YOLO model from a vailá/getpixelvideo YOLO dataset."""
    config = _resolve_training_config(
        yaml_file,
        task=task,
        model=model,
        epochs=epochs,
        batch=batch,
        imgsz=imgsz,
        device=device,
        project=project,
        name=name,
    )
    if dry_run:
        return config

    model_path = _model_path_for_training(config.model_name)
    yolo_model = YOLO(model_path)
    train_kwargs = {
        "data": config.yaml_file,
        "epochs": config.epochs,
        "batch": config.batch,
        "imgsz": config.imgsz,
        "device": config.device,
        "project": config.project,
        "name": config.name,
        "exist_ok": exist_ok,
        "verbose": True,
    }
    train_kwargs.update(extra_train_args or {})
    return yolo_model.train(**train_kwargs)


# --- Class to redirect the console output to the Text Widget ---
class ConsoleRedirector:
    """Redirects stdout to both GUI and terminal."""

    def __init__(self, text_widget):
        self.text_widget = text_widget
        self.original_stdout = sys.stdout

    def write(self, text):
        # Write to GUI
        self.text_widget.insert(tk.END, text)
        self.text_widget.see(tk.END)
        self.text_widget.update_idletasks()

        # Also write to original terminal
        self.original_stdout.write(text)
        self.original_stdout.flush()

    def flush(self):
        self.original_stdout.flush()


# --- Main Application Class ---
class YOLOTrainApp(tk.Tk):
    """YOLO Training Interface for vailá/getpixelvideo and YOLO datasets."""

    def __init__(self):
        super().__init__()
        self.title("YOLO26 Training - vailá datasets")
        self.geometry("980x760")
        self.configure(padx=10, pady=10)

        # Keep older model families available, but make YOLO26 the default path.
        self.available_models = [
            AUTO_MODEL_LABEL,
            *YOLO26_MODELS,
            "yolo11n.pt",
            "yolo11s.pt",
            "yolo11m.pt",
            "yolo11l.pt",
            "yolo11x.pt",
            "yolo11n-pose.pt",
            "yolo11s-pose.pt",
            "yolo11m-pose.pt",
            "yolo11l-pose.pt",
            "yolo11x-pose.pt",
            "yolov8n.pt",
            "yolov8s.pt",
            "yolov8m.pt",
            "yolov8l.pt",
            "yolov8x.pt",
            "yolov9c.pt",
            "yolov9e.pt",
            "yolov9l.pt",
            "yolov9m.pt",
            "yolov9s.pt",
        ]

        # Tkinter variables
        self.dataset_path = tk.StringVar()
        self.yaml_path = tk.StringVar()
        self.task_var = tk.StringVar(value="auto")
        self.base_model = tk.StringVar(value=AUTO_MODEL_LABEL)
        self.epochs_var = tk.StringVar(value="100")
        self.batch_var = tk.StringVar(value="16")
        self.imgsz_var = tk.StringVar(value="640")
        self.device_var = tk.StringVar(value="auto")
        self.project_name = tk.StringVar(value="yolo_training")

        self.create_widgets()

    def create_widgets(self):
        """Create the YOLO training GUI."""
        self.grid_rowconfigure(11, weight=1)
        self.grid_columnconfigure(1, weight=1)

        title_label = tk.Label(
            self,
            text="YOLO26 Training - vailá getpixelvideo / SAM datasets",
            font=("Arial", 16, "bold"),
        )
        title_label.grid(row=0, column=0, columnspan=3, pady=10)

        help_button = tk.Button(
            self,
            text="Dataset Guide",
            command=self.show_dataset_help,
            bg="#2196F3",
            fg="white",
            font=("Arial", 10),
        )
        help_button.grid(row=1, column=0, columnspan=3, pady=5)

        model_info_label = tk.Label(
            self,
            text="Select a data.yaml generated by getpixelvideo.py, vaila_sam.py -> getpixelvideo, or any Ultralytics YOLO dataset.",
            font=("Arial", 9),
            fg="#666666",
        )
        model_info_label.grid(row=2, column=0, columnspan=3, pady=2)

        tk.Label(self, text="Dataset Folder:").grid(row=3, column=0, sticky="e", padx=5, pady=5)
        dataset_entry = tk.Entry(self, textvariable=self.dataset_path, width=58, state="readonly")
        dataset_entry.grid(row=3, column=1, padx=5, pady=5, sticky="ew")
        tk.Button(self, text="Browse", command=self.browse_dataset).grid(
            row=3, column=2, padx=5, pady=5
        )

        yaml_frame = tk.Frame(self)
        yaml_frame.grid(row=4, column=0, columnspan=3, pady=5, sticky="ew")
        yaml_frame.grid_columnconfigure(0, weight=1)
        tk.Label(yaml_frame, text="data.yaml:").grid(row=0, column=0, sticky="w", padx=5)
        yaml_entry = tk.Entry(yaml_frame, textvariable=self.yaml_path, width=58, state="readonly")
        yaml_entry.grid(row=1, column=0, padx=5, pady=2, sticky="ew")
        yaml_buttons_frame = tk.Frame(yaml_frame)
        yaml_buttons_frame.grid(row=1, column=1, padx=5, pady=2)
        tk.Button(yaml_buttons_frame, text="Browse YAML", command=self.browse_yaml).grid(
            row=0, column=0, padx=2
        )
        tk.Button(yaml_buttons_frame, text="Create YAML", command=self.create_new_yaml).grid(
            row=0, column=1, padx=2
        )

        train_frame = tk.LabelFrame(self, text="Training")
        train_frame.grid(row=5, column=0, columnspan=3, padx=5, pady=8, sticky="ew")
        for col in (1, 3):
            train_frame.grid_columnconfigure(col, weight=1)

        tk.Label(train_frame, text="Task:").grid(row=0, column=0, sticky="e", padx=5, pady=4)
        task_combo = ttk.Combobox(
            train_frame,
            textvariable=self.task_var,
            values=TASK_CHOICES,
            state="readonly",
            width=14,
        )
        task_combo.grid(row=0, column=1, sticky="ew", padx=5, pady=4)
        task_combo.bind("<<ComboboxSelected>>", self._update_model_list)

        tk.Label(train_frame, text="Model:").grid(row=0, column=2, sticky="e", padx=5, pady=4)
        self.model_combo = ttk.Combobox(
            train_frame,
            textvariable=self.base_model,
            values=self.available_models,
            width=26,
        )
        self.model_combo.grid(row=0, column=3, sticky="ew", padx=5, pady=4)

        tk.Button(train_frame, text="Model Guide", command=self.show_model_help).grid(
            row=0, column=4, padx=5, pady=4
        )

        tk.Label(train_frame, text="Epochs:").grid(row=1, column=0, sticky="e", padx=5, pady=4)
        tk.Entry(train_frame, textvariable=self.epochs_var, width=12).grid(
            row=1, column=1, sticky="ew", padx=5, pady=4
        )
        tk.Label(train_frame, text="Batch:").grid(row=1, column=2, sticky="e", padx=5, pady=4)
        tk.Entry(train_frame, textvariable=self.batch_var, width=12).grid(
            row=1, column=3, sticky="ew", padx=5, pady=4
        )

        tk.Label(train_frame, text="Image size:").grid(row=2, column=0, sticky="e", padx=5, pady=4)
        tk.Entry(train_frame, textvariable=self.imgsz_var, width=12).grid(
            row=2, column=1, sticky="ew", padx=5, pady=4
        )
        tk.Label(train_frame, text="Device:").grid(row=2, column=2, sticky="e", padx=5, pady=4)
        tk.Entry(train_frame, textvariable=self.device_var, width=12).grid(
            row=2, column=3, sticky="ew", padx=5, pady=4
        )

        tk.Label(train_frame, text="Run name:").grid(row=3, column=0, sticky="e", padx=5, pady=4)
        tk.Entry(train_frame, textvariable=self.project_name, width=26).grid(
            row=3, column=1, columnspan=3, sticky="ew", padx=5, pady=4
        )

        self.csv_button = tk.Button(
            self,
            text="Legacy helper: build detect dataset from getpixelvideo marker CSV",
            command=self.create_dataset_from_getpixelvideo_csv,
            bg="#673AB7",
            fg="white",
        )
        self.csv_button.grid(row=6, column=0, columnspan=3, pady=5, sticky="ew")

        self.start_button = tk.Button(
            self,
            text="Start Training",
            command=self.start_training_thread,
            bg="#4CAF50",
            fg="white",
            font=("Arial", 12, "bold"),
            height=2,
        )
        self.start_button.grid(row=7, column=0, columnspan=3, pady=10, sticky="ew")

        tk.Label(self, text="Training Output:").grid(
            row=8, column=0, columnspan=3, sticky="w", padx=5, pady=5
        )
        self.console = scrolledtext.ScrolledText(self, height=18, wrap="word", font=("Consolas", 9))
        self.console.grid(row=9, column=0, columnspan=3, padx=10, pady=5, sticky="nsew")
        self._update_model_list()

    def _update_model_list(self, event=None):
        """Filter model suggestions by selected task while keeping free text paths allowed."""
        task = self.task_var.get()
        if task == "pose":
            models = [AUTO_MODEL_LABEL] + [m for m in self.available_models if "-pose" in m]
        elif task == "segment":
            models = [AUTO_MODEL_LABEL] + [m for m in self.available_models if "-seg" in m]
        elif task == "detect":
            models = [AUTO_MODEL_LABEL] + [
                m
                for m in self.available_models
                if m != AUTO_MODEL_LABEL and "-pose" not in m and "-seg" not in m
            ]
        else:
            models = self.available_models
        self.model_combo["values"] = models
        if self.base_model.get() not in models and self.base_model.get() != "auto":
            self.base_model.set(AUTO_MODEL_LABEL)

    def show_model_help(self):
        """Shows help information about YOLO models."""
        help_text = """
YOLO MODEL GUIDE
================

AUTO MODEL:
- The default "auto" option reads data.yaml and chooses YOLO26 by task:
  detect  -> yolo26m.pt
  pose    -> yolo26m-pose.pt
  segment -> yolo26m-seg.pt

DATASET TASKS:
- detect: bbox labels, generated by getpixelvideo bbox export or legacy CSV helper
- pose: YOLO-pose labels with kpt_shape, generated by getpixelvideo F9
- segment: polygon/mask labels with a *-seg.pt model

MODEL SIZES (n -> s -> m -> l -> x):
- n/s: faster, lower VRAM
- m: default balance
- l/x: slower, higher VRAM

Custom .pt paths are accepted in the Model field.
        """

        messagebox.showinfo("YOLO Model Guide", help_text)

    def show_dataset_help(self):
        """Shows supported dataset help."""
        help_text = """
YOLO DATASET GUIDE
==================

1. DATASETS CREATED IN VAILA
   - getpixelvideo F5 / bbox export: YOLO detect dataset
   - getpixelvideo F9: YOLO-pose dataset with kpt_shape in data.yaml
   - vaila_sam.py -> getpixelvideo: load SAM tracks, choose bbox/marker workflow,
     then export the YOLO dataset from getpixelvideo

2. SUPPORTED ULTRALYTICS LAYOUTS
   vailá layout:
     train/images + train/labels
     val/images   + val/labels
     test/images  + test/labels (optional)

   FIFA/Ultralytics layout:
     images/train + labels/train
     images/val   + labels/val
     images/test  + labels/test (optional)

3. TRAINING
   - Browse the dataset folder or its data.yaml
   - Keep Task and Model as auto unless overriding intentionally
   - Start Training

4. LEGACY CSV HELPER
   The purple CSV button is only for older getpixelvideo marker CSV files that
   do not already have a YOLO dataset. Current getpixelvideo exports should be
   selected directly by data.yaml.
        """

        messagebox.showinfo("Dataset Guide", help_text)

    def _refresh_from_yaml(self, yaml_file):
        """Update GUI task/model hints after a data.yaml selection."""
        try:
            yaml_data = _load_yaml(yaml_file)
            task = _detect_task_from_yaml(yaml_data, os.path.dirname(yaml_file))
            self.task_var.set(task)
            self.base_model.set(AUTO_MODEL_LABEL)
            self._update_model_list()
            self._append_console(
                f"Loaded data.yaml: task={task}, auto model={DEFAULT_MODEL_BY_TASK.get(task)}"
            )
        except Exception as exc:
            self._append_console(f"Could not inspect YAML yet: {exc}")

    def browse_dataset(self):
        """Browse for a YOLO dataset folder."""
        path = filedialog.askdirectory(title="Select YOLO Dataset Folder")

        if path:
            self.dataset_path.set(path)
            yaml_file = os.path.join(path, "data.yaml")
            if os.path.exists(yaml_file):
                self.yaml_path.set(yaml_file)
                self._refresh_from_yaml(yaml_file)
                messagebox.showinfo(
                    "YAML Found",
                    f"Found existing data.yaml:\n{yaml_file}\n\n"
                    "Task/model will be detected automatically.",
                )
            else:
                result = messagebox.askyesno(
                    "Create YAML",
                    f"No data.yaml found in:\n{path}\n\nCreate one from the detected YOLO folders?",
                )
                if result:
                    self._auto_detect_and_create_yaml(path)

    def browse_yaml(self):
        """Browse for existing YAML file."""
        initialdir = self.dataset_path.get() or os.getcwd()
        yaml_file = filedialog.askopenfilename(
            title="Select data.yaml",
            filetypes=[("YAML files", "*.yaml *.yml"), ("All files", "*.*")],
            initialdir=initialdir,
        )

        if yaml_file:
            self.yaml_path.set(yaml_file)
            self.dataset_path.set(os.path.dirname(yaml_file))
            self._refresh_from_yaml(yaml_file)
            print(f"Selected YAML file: {yaml_file}")

    def create_new_yaml(self):
        """Create new YAML file for current dataset."""
        if not self.dataset_path.get():
            messagebox.showwarning("Warning", "Please select a dataset folder first!")
            return

        # Ask for confirmation
        result = messagebox.askyesno(
            "Create New YAML",
            "This will create a new YAML file with default settings.\n"
            "Any existing YAML will be overwritten.\n\n"
            "Continue?",
        )

        if result:
            success = self._auto_detect_and_create_yaml(self.dataset_path.get())
            if success:
                print(f"New YAML created: {self.yaml_path.get()}")

    def create_dataset_from_getpixelvideo_csv(self):
        """Create a YOLO detection/tracking dataset from getpixelvideo point CSV + video.

        Heavy work (CSV parsing + sequential frame extraction) runs in a worker
        thread to keep the Tk main loop responsive on large CSVs.
        """
        csv_path = filedialog.askopenfilename(
            title="Select getpixelvideo / sam_points_georeid CSV",
            filetypes=[("CSV files", "*.csv"), ("All files", "*.*")],
        )
        if not csv_path:
            return

        video_path = filedialog.askopenfilename(
            title="Select source video for this CSV",
            filetypes=[
                ("Video files", "*.mp4 *.avi *.mov *.mkv *.MP4 *.AVI *.MOV *.MKV"),
                ("All files", "*.*"),
            ],
            initialdir=os.path.dirname(csv_path),
        )
        if not video_path:
            return

        class_name = simpledialog.askstring(
            "Class name",
            "YOLO class name for each marked point:",
            initialvalue="object",
            parent=self,
        )
        if not class_name:
            return
        class_name = " ".join(class_name.strip().split()) or "object"

        box_size = simpledialog.askinteger(
            "Box size",
            "Fixed box size in pixels around each point:",
            initialvalue=48,
            minvalue=4,
            maxvalue=512,
            parent=self,
        )
        if not box_size:
            return

        output_parent = filedialog.askdirectory(
            title="Select output folder for the generated dataset",
            initialdir=os.path.dirname(csv_path),
        )
        if not output_parent:
            return

        self._set_dataset_button_state("disabled")
        self._append_console("Building YOLO dataset in background thread...")
        worker = threading.Thread(
            target=self._dataset_build_worker,
            kwargs={
                "csv_path": csv_path,
                "video_path": video_path,
                "output_parent": output_parent,
                "class_name": class_name,
                "box_size": float(box_size),
            },
            daemon=True,
        )
        worker.start()

    def _set_dataset_button_state(self, state):
        """Toggle the CSV-dataset button so the user can't queue parallel builds."""
        button = getattr(self, "csv_button", None)
        if button is not None:
            with contextlib.suppress(tk.TclError):
                button.configure(state=state)

    def _append_console(self, message):
        """Thread-safe-friendly console append (call only from the Tk main thread)."""
        self.console.insert(tk.END, message + "\n")
        self.console.see(tk.END)

    def _dataset_build_worker(self, csv_path, video_path, output_parent, class_name, box_size):
        """Run the dataset build off the Tk main thread; marshal results back via after()."""
        try:
            dataset_dir, yaml_file, message = self._build_tracking_dataset_from_pixel_csv(
                csv_path=csv_path,
                video_path=video_path,
                output_parent=output_parent,
                class_name=class_name,
                box_size=box_size,
                progress_callback=lambda msg: self.after(0, self._append_console, msg),
            )
        except Exception as exc:
            self.after(0, self._on_dataset_build_failed, str(exc))
            return
        self.after(0, self._on_dataset_build_succeeded, dataset_dir, yaml_file, message)

    def _on_dataset_build_failed(self, exc_msg):
        self._set_dataset_button_state("normal")
        self._append_console(f"Dataset build failed: {exc_msg}")
        messagebox.showerror("Dataset Error", f"Failed to create dataset:\n\n{exc_msg}")

    def _on_dataset_build_succeeded(self, dataset_dir, yaml_file, message):
        self._set_dataset_button_state("normal")
        self.dataset_path.set(dataset_dir)
        self.yaml_path.set(yaml_file)
        self._append_console(message)
        messagebox.showinfo("Dataset Created", message)

    def _build_tracking_dataset_from_pixel_csv(
        self,
        csv_path,
        video_path,
        output_parent,
        class_name,
        box_size,
        progress_callback=None,
    ):
        """Convert frame,pN_x,pN_y CSV markers into YOLO detect labels.

        Frames are read **sequentially** with cap.grab()/retrieve(); the previous
        implementation seeked in shuffled order via cap.set(POS_FRAMES, ...),
        which is both slow (keyframe re-decode per row) and codec-inaccurate
        (target frame may land on a neighbor). Iterating in ascending frame
        order also makes the build O(max_frame) instead of O(N_rows * seek).
        Split assignment is still random, but each frame is decoded once and
        each frame belongs to exactly one split (no train -> val duplication).
        """

        def report(msg):
            if progress_callback is not None:
                with contextlib.suppress(Exception):
                    progress_callback(msg)

        df = pd.read_csv(csv_path)
        if "frame" not in df.columns:
            raise ValueError("CSV must contain a 'frame' column.")

        point_ids = sorted(
            {
                col[1:-2]
                for col in df.columns
                if col.startswith("p") and col.endswith("_x") and col[1:-2].isdigit()
            },
            key=lambda value: int(value),
        )
        if not point_ids:
            raise ValueError("No pN_x/pN_y columns found in CSV.")

        cap = cv2.VideoCapture(video_path)
        if not cap.isOpened():
            raise ValueError(f"Could not open video: {video_path}")

        try:
            width = int(cap.get(cv2.CAP_PROP_FRAME_WIDTH))
            height = int(cap.get(cv2.CAP_PROP_FRAME_HEIGHT))
            if width <= 0 or height <= 0:
                raise ValueError("Could not read video width/height.")

            video_stem = pathlib.Path(video_path).stem
            out_dir = (
                pathlib.Path(output_parent)
                / f"yolo_tracking_{video_stem}_{datetime.now():%Y%m%d_%H%M%S}"
            )

            valid_rows = []
            for _row_index, row in df.iterrows():
                frame_value = pd.to_numeric(row.get("frame"), errors="coerce")
                if pd.isna(frame_value) or frame_value < 0:
                    continue
                labels = []
                for point_id in point_ids:
                    point = self._row_point(row, point_id)
                    if point is None:
                        continue
                    x_px, y_px = point
                    labels.append(self._point_to_yolo_label(x_px, y_px, box_size, width, height))
                if labels:
                    valid_rows.append((int(frame_value), labels))

            if not valid_rows:
                raise ValueError("CSV has no visible points to export.")

            n_total = len(valid_rows)
            if n_total < 2:
                # Refuse to fabricate val by duplicating the single train row,
                # which would silently leak training data into validation.
                raise ValueError(
                    "Need at least 2 frames with visible points to build a "
                    "train/val split (got 1). Annotate more frames first."
                )

            # Allocate train and val first (both guaranteed >=1), test takes the rest.
            n_train = max(1, round(n_total * 0.7))
            n_train = min(n_train, n_total - 1)  # always leave at least 1 row for val
            remaining = n_total - n_train
            n_val = max(1, round(n_total * 0.2))
            n_val = min(n_val, remaining)
            n_test = remaining - n_val

            # Shuffle once for split assignment, then sort *within each split*
            # so the actual video decode below is purely ascending.
            shuffled = list(valid_rows)
            random.shuffle(shuffled)
            train_rows = sorted(shuffled[:n_train], key=lambda x: x[0])
            val_rows = sorted(shuffled[n_train : n_train + n_val], key=lambda x: x[0])
            test_rows = sorted(shuffled[n_train + n_val :], key=lambda x: x[0])

            # Materialize the per-frame split assignment. Disjoint slices of
            # `shuffled` guarantee a given frame never appears in two splits.
            frame_to_split: dict[int, tuple[str, list[str]]] = {}
            for frame_num, labels in train_rows:
                frame_to_split[frame_num] = ("train", labels)
            for frame_num, labels in val_rows:
                frame_to_split[frame_num] = ("val", labels)
            for frame_num, labels in test_rows:
                frame_to_split[frame_num] = ("test", labels)

            # Only create directories for splits we will actually populate.
            active_splits = {split for split, _ in frame_to_split.values()}
            for split in active_splits:
                (out_dir / split / "images").mkdir(parents=True, exist_ok=True)
                (out_dir / split / "labels").mkdir(parents=True, exist_ok=True)

            sorted_targets = sorted(frame_to_split.keys())
            report(
                f"Extracting {len(sorted_targets)} frames sequentially "
                f"(train={n_train}, val={n_val}, test={n_test})..."
            )

            written = {"train": 0, "val": 0, "test": 0}
            target_idx = 0
            current_frame = 0
            progress_every = max(1, len(sorted_targets) // 20)

            while target_idx < len(sorted_targets):
                target = sorted_targets[target_idx]
                # Skip frames before the target with grab() (no decode cost).
                reached = True
                while current_frame < target:
                    if not cap.grab():
                        reached = False
                        break
                    current_frame += 1
                if not reached:
                    unreachable = len(sorted_targets) - target_idx
                    report(
                        f"Reached end of video; {unreachable} target frames "
                        f"are beyond the last decoded frame ({current_frame - 1})."
                    )
                    break

                ok, frame = cap.read()
                current_frame += 1
                if not ok or frame is None:
                    target_idx += 1
                    continue

                split, labels = frame_to_split[target]
                image_name = f"{video_stem}_frame_{target:06d}.jpg"
                label_name = f"{video_stem}_frame_{target:06d}.txt"
                cv2.imwrite(str(out_dir / split / "images" / image_name), frame)
                with open(out_dir / split / "labels" / label_name, "w", encoding="utf-8") as f:
                    f.write("\n".join(labels) + "\n")
                written[split] += 1
                target_idx += 1

                if target_idx % progress_every == 0:
                    report(
                        f"  {target_idx}/{len(sorted_targets)} frames extracted "
                        f"(train={written['train']}, val={written['val']}, "
                        f"test={written['test']})"
                    )

            if written["train"] == 0 or written["val"] == 0:
                raise ValueError(
                    "Could not extract enough video frames for train/val splits "
                    f"(written train={written['train']}, val={written['val']}). "
                    "Check that CSV frame numbers match the video."
                )

            with open(out_dir / "classes.txt", "w", encoding="utf-8") as f:
                f.write(class_name + "\n")

            train_path = (out_dir / "train" / "images").resolve().as_posix()
            val_path = (out_dir / "val" / "images").resolve().as_posix()
            test_path = (out_dir / "test" / "images").resolve().as_posix()
            yaml_file = out_dir / "data.yaml"
            yaml_file.write_text(
                "# YOLO detection/tracking dataset - generated by vaila yolotrain\n"
                f"path: {out_dir.resolve().as_posix()}\n"
                f"train: {train_path}\n"
                f"val: {val_path}\n"
                f"test: {test_path}\n"
                "nc: 1\n"
                f"names: {[class_name]!r}\n"
                "\n"
                "# Training defaults editable before Start Training\n"
                "model: yolo26m.pt\n"
                "epochs: 100\n"
                "batch: 16\n"
                "imgsz: 640\n"
                "device: cpu\n",
                encoding="utf-8",
            )

            message = (
                "YOLO tracking dataset created from getpixelvideo CSV:\n"
                f"  Dataset: {out_dir}\n"
                f"  CSV: {csv_path}\n"
                f"  Video: {video_path}\n"
                f"  Class: {class_name}\n"
                f"  Points exported as fixed {int(box_size)} px boxes\n"
                f"  Train/Val/Test images: "
                f"{written['train']}/{written['val']}/{written['test']}\n"
                f"  YAML: {yaml_file}"
            )
            return str(out_dir), str(yaml_file), message
        finally:
            cap.release()

    @staticmethod
    def _row_point(row, point_id):
        """Return pN point, preferring edited x/y and falling back to mask/centroid columns."""
        candidates = (
            (f"p{point_id}_x", f"p{point_id}_y"),
            (f"p{point_id}_mx", f"p{point_id}_my"),
            (f"p{point_id}_cx", f"p{point_id}_cy"),
        )
        for x_col, y_col in candidates:
            if x_col not in row.index or y_col not in row.index:
                continue
            x_val = pd.to_numeric(row.get(x_col), errors="coerce")
            y_val = pd.to_numeric(row.get(y_col), errors="coerce")
            if pd.isna(x_val) or pd.isna(y_val):
                continue
            return float(x_val), float(y_val)
        return None

    @staticmethod
    def _point_to_yolo_label(x_px, y_px, box_size, width, height):
        """Build one YOLO detect label line from a center point and fixed box size."""
        half = box_size / 2.0
        x1 = max(0.0, x_px - half)
        y1 = max(0.0, y_px - half)
        x2 = min(float(width), x_px + half)
        y2 = min(float(height), y_px + half)
        box_w = max(1.0, x2 - x1)
        box_h = max(1.0, y2 - y1)
        cx = (x1 + box_w / 2.0) / float(width)
        cy = (y1 + box_h / 2.0) / float(height)
        return f"0 {cx:.6f} {cy:.6f} {box_w / width:.6f} {box_h / height:.6f}"

    @staticmethod
    def _resolve_yaml_path(yaml_data, dataset_dir, key):
        """Resolve Ultralytics train/val/test path entries."""
        return _resolve_yaml_path_entry(yaml_data, dataset_dir, key)

    @staticmethod
    def _detect_dataset_split_paths(dataset_path):
        """Detect vailá or FIFA/Ultralytics split folder layouts."""
        vaila_train = os.path.join(dataset_path, "train", "images")
        vaila_val = os.path.join(dataset_path, "val", "images")
        fifa_train = os.path.join(dataset_path, "images", "train")
        fifa_val = os.path.join(dataset_path, "images", "val")
        if os.path.isdir(vaila_train) and os.path.isdir(vaila_val):
            return {
                "layout": "vaila",
                "train": vaila_train,
                "val": vaila_val,
                "test": os.path.join(dataset_path, "test", "images"),
            }
        if os.path.isdir(fifa_train) and os.path.isdir(fifa_val):
            return {
                "layout": "fifa",
                "train": fifa_train,
                "val": fifa_val,
                "test": os.path.join(dataset_path, "images", "test"),
            }
        return None

    def _auto_detect_and_create_yaml(self, dataset_path):
        """Detect YOLO folder layout and create data.yaml."""
        split_paths = self._detect_dataset_split_paths(dataset_path)
        if not split_paths:
            messagebox.showerror(
                "YOLO Dataset Not Found",
                "Expected one of these layouts:\n\n"
                "  train/images + train/labels\n"
                "  val/images   + val/labels\n\n"
                "or\n\n"
                "  images/train + labels/train\n"
                "  images/val   + labels/val\n\n"
                f"Selected folder:\n{dataset_path}",
            )
            return False

        class_names = _read_classes_txt(dataset_path)
        if not class_names:
            class_names = ["object"]

        train_path = os.path.abspath(split_paths["train"]).replace("\\", "/")
        val_path = os.path.abspath(split_paths["val"]).replace("\\", "/")
        test_path_raw = split_paths["test"]
        test_path = (
            os.path.abspath(test_path_raw).replace("\\", "/")
            if test_path_raw and os.path.isdir(test_path_raw)
            else None
        )

        yaml_content = self._create_comprehensive_yaml(
            train_path,
            val_path,
            test_path,
            class_names,
            task="detect",
        )
        yaml_file_path = os.path.join(dataset_path, "data.yaml")

        try:
            with open(yaml_file_path, "w", encoding="utf-8") as f:
                f.write(yaml_content)

            self.yaml_path.set(yaml_file_path)
            self.dataset_path.set(dataset_path)
            self._refresh_from_yaml(yaml_file_path)
            train_count = _image_count(split_paths["train"])
            val_count = _image_count(split_paths["val"])

            messagebox.showinfo(
                "Success",
                "Dataset ready for training.\n\n"
                f"Classes: {len(class_names)}\n"
                f"Train images: {train_count}\n"
                f"Val images: {val_count}\n"
                f"YAML: {yaml_file_path}",
            )

            return True

        except Exception as e:
            messagebox.showerror("Error", f"Failed to create YAML: {str(e)}")
            return False

    def _create_comprehensive_yaml(
        self, train_path, val_path, test_path, class_names, task="detect"
    ):
        """Create a compact Ultralytics data.yaml with YOLO26 defaults."""
        if not class_names:
            class_names = ["object"]
        names_str = str(class_names)
        test_line = f"\ntest: {test_path}" if test_path else ""
        model_name = DEFAULT_MODEL_BY_TASK.get(task, DEFAULT_MODEL_BY_TASK["detect"])
        yaml_content = f"""# YOLO dataset - generated by vailá yolotrain
path: .
train: {train_path}
val: {val_path}{test_line}
nc: {len(class_names)}
names: {names_str}

# Training defaults used by vaila/yolotrain.py when GUI fields are auto/blank
task: {task}
model: {model_name}
epochs: 100
batch: 16
imgsz: 640
device: auto
"""
        return yaml_content

    @staticmethod
    def _blank_to_none(value):
        text = str(value or "").strip()
        return None if text == "" else text

    def _gui_training_config(self):
        model_value = self._blank_to_none(self.base_model.get()) or "auto"
        if model_value == AUTO_MODEL_LABEL:
            model_value = "auto"
        return _resolve_training_config(
            self.yaml_path.get(),
            task=self.task_var.get(),
            model=model_value,
            epochs=self._blank_to_none(self.epochs_var.get()),
            batch=self._blank_to_none(self.batch_var.get()),
            imgsz=self._blank_to_none(self.imgsz_var.get()),
            device=self._blank_to_none(self.device_var.get()) or "auto",
            name=self.project_name.get(),
        )

    def start_training_thread(self):
        """Starts training in a separate thread."""
        if not self.yaml_path.get():
            messagebox.showerror(
                "Error", "No data.yaml selected. Browse a dataset folder or data.yaml first."
            )
            return

        if not self._validate_existing_yaml(self.yaml_path.get()):
            return

        self.start_button.config(state=tk.DISABLED)
        self.console.delete("1.0", tk.END)
        self.console.insert(tk.END, "Starting training...\n")

        training_thread = threading.Thread(target=self._run_training)
        training_thread.daemon = True
        training_thread.start()

    def _run_training(self):
        """Runs the YOLO training."""
        original_stdout = sys.stdout
        sys.stdout = ConsoleRedirector(self.console)

        try:
            config = self._gui_training_config()
            self.dataset_path.set(config.dataset_dir)

            print("=" * 60)
            print("YOLO TRAINING STARTING")
            print("=" * 60)
            print(f"Dataset folder: {config.dataset_dir}")
            print(f"YAML file: {config.yaml_file}")
            print(f"Detected task: {config.task}")
            print(f"Model: {config.model_name}")
            print(f"Run name: {config.name}")
            print("=" * 60)

            print("\nValidated dataset:")
            print(f"  Train path: {config.train_path} ({_image_count(config.train_path)} images)")
            print(f"  Val path: {config.val_path} ({_image_count(config.val_path)} images)")

            print("\nTraining parameters:")
            print(f"  Epochs: {config.epochs}")
            print(f"  Batch size: {config.batch}")
            print(f"  Image size: {config.imgsz}")
            print(f"  Device: {config.device}")

            print("\n--- MODEL INFORMATION ---")
            print(f"Selected model: {config.model_name}")
            self._show_model_characteristics(config.model_name)
            print("Resolving model weights under vaila/models when needed...")
            model_path = _model_path_for_training(config.model_name)
            if os.path.exists(model_path):
                size_mb = os.path.getsize(model_path) / (1024 * 1024)
                print(f"Model path: {model_path} ({size_mb:.1f} MB)")
            else:
                print(f"Model reference: {model_path}")

            print(f"\nLoading model: {config.model_name}")
            model = YOLO(model_path)
            print("Model loaded successfully")

            run_output_dir = os.path.join(config.project, config.name)
            weights_dir = os.path.join(run_output_dir, "weights")

            print("\n--- Training Configuration ---")
            print(f"Dataset: {config.dataset_dir}")
            print(f"YAML: {config.yaml_file}")
            print(f"Task: {config.task}")
            print(f"Model: {config.model_name}")
            print(f"Epochs: {config.epochs}")
            print(f"Batch Size: {config.batch}")
            print(f"Image Size: {config.imgsz}")
            print(f"Device: {config.device}")
            print(f"Output Directory: {config.project}")
            print(f"Run Directory: {run_output_dir}")
            print(f"Weights Directory: {weights_dir}")
            print("-----------------------------\n")

            print("Starting YOLO training...")
            print("Training progress will be shown below:\n")

            results = model.train(  # noqa: F841 - keep result object for future diagnostics
                data=config.yaml_file,
                epochs=config.epochs,
                batch=config.batch,
                imgsz=config.imgsz,
                device=config.device,
                project=config.project,
                name=config.name,
                exist_ok=True,
                verbose=True,
            )

            best_model_path = os.path.join(weights_dir, "best.pt")
            last_model_path = os.path.join(weights_dir, "last.pt")

            print("\n" + "=" * 60)
            print("TRAINING COMPLETED SUCCESSFULLY!")
            print("=" * 60)
            print("OUTPUT LOCATIONS:")
            print(f"   Best model: {best_model_path}")
            print(f"   Last model: {last_model_path}")
            print(f"   Results folder: {run_output_dir}")
            print(f"   Weights folder: {weights_dir}")
            print("=" * 60)

            self._show_model_info(best_model_path, last_model_path, run_output_dir)

            def show_completion():
                result = messagebox.askyesno(
                    "Training Completed",
                    f"Training completed successfully!\n\n"
                    f"OUTPUT LOCATIONS:\n"
                    f"   Best model: {best_model_path}\n"
                    f"   Last model: {last_model_path}\n"
                    f"   Results folder: {run_output_dir}\n\n"
                    f"Open results folder?",
                )

                if result:
                    if sys.platform == "win32":
                        os.startfile(run_output_dir)
                    elif sys.platform == "darwin":
                        os.system(f"open '{run_output_dir}'")
                    else:
                        os.system(f"xdg-open '{run_output_dir}'")

            self.after(0, show_completion)

        except Exception as e:
            error_msg = str(e)
            print("\n" + "=" * 60)
            print("TRAINING ERROR!")
            print("=" * 60)
            print(f"Error type: {type(e).__name__}")
            print(f"Error message: {error_msg}")
            print("=" * 60)

            original_stdout.write(f"\nTRAINING ERROR: {error_msg}\n")
            original_stdout.flush()

            error_type = type(e).__name__
            self.after(
                0,
                lambda: messagebox.showerror(
                    "Training Error",
                    f"Error during training:\n\n"
                    f"Type: {error_type}\n"
                    f"Message: {error_msg}\n\n"
                    f"Check the console output above for details.",
                ),
            )
        finally:
            sys.stdout = original_stdout
            self.after(0, lambda: self.start_button.config(state=tk.NORMAL))

    def _show_model_characteristics(self, model_name):
        """Shows characteristics of the selected model."""
        print("\nModel characteristics:")

        # Model size and performance characteristics
        model_info = {
            # YOLO26 Models (Latest - 2026)
            "yolo26n.pt": {
                "size": "~6MB",
                "speed": "Fastest",
                "accuracy": "Lower",
                "use": "Edge devices, real-time",
            },
            "yolo26s.pt": {
                "size": "~20MB",
                "speed": "Fast",
                "accuracy": "Low",
                "use": "Mobile, embedded",
            },
            "yolo26m.pt": {
                "size": "~50MB",
                "speed": "Medium",
                "accuracy": "Good",
                "use": "General purpose (recommended)",
            },
            "yolo26l.pt": {
                "size": "~150MB",
                "speed": "Slow",
                "accuracy": "High",
                "use": "High accuracy needed",
            },
            "yolo26x.pt": {
                "size": "~300MB",
                "speed": "Slowest",
                "accuracy": "Highest",
                "use": "Best accuracy",
            },
            # YOLO11 Models
            "yolo11n.pt": {
                "size": "~6MB",
                "speed": "Fastest",
                "accuracy": "Lower",
                "use": "Edge devices, real-time",
            },
            "yolo11s.pt": {
                "size": "~20MB",
                "speed": "Fast",
                "accuracy": "Low",
                "use": "Mobile, embedded",
            },
            "yolo11m.pt": {
                "size": "~50MB",
                "speed": "Medium",
                "accuracy": "Good",
                "use": "General purpose",
            },
            "yolo11l.pt": {
                "size": "~150MB",
                "speed": "Slow",
                "accuracy": "High",
                "use": "High accuracy needed",
            },
            "yolo11x.pt": {
                "size": "~300MB",
                "speed": "Slowest",
                "accuracy": "Highest",
                "use": "Best accuracy",
            },
            # YOLOv8 Models
            "yolov8n.pt": {
                "size": "~6MB",
                "speed": "Fastest",
                "accuracy": "Lower",
                "use": "Edge devices, real-time",
            },
            "yolov8s.pt": {
                "size": "~20MB",
                "speed": "Fast",
                "accuracy": "Low",
                "use": "Mobile, embedded",
            },
            "yolov8m.pt": {
                "size": "~50MB",
                "speed": "Medium",
                "accuracy": "Good",
                "use": "General purpose",
            },
            "yolov8l.pt": {
                "size": "~150MB",
                "speed": "Slow",
                "accuracy": "High",
                "use": "High accuracy needed",
            },
            "yolov8x.pt": {
                "size": "~300MB",
                "speed": "Slowest",
                "accuracy": "Highest",
                "use": "Best accuracy",
            },
            # YOLOv9 Models
            "yolov9c.pt": {
                "size": "~10MB",
                "speed": "Fast",
                "accuracy": "Low",
                "use": "Compact, efficient",
            },
            "yolov9s.pt": {
                "size": "~20MB",
                "speed": "Fast",
                "accuracy": "Low",
                "use": "Mobile, embedded",
            },
            "yolov9m.pt": {
                "size": "~50MB",
                "speed": "Medium",
                "accuracy": "Good",
                "use": "General purpose",
            },
            "yolov9l.pt": {
                "size": "~150MB",
                "speed": "Slow",
                "accuracy": "High",
                "use": "High accuracy needed",
            },
            "yolov9e.pt": {
                "size": "~300MB",
                "speed": "Slowest",
                "accuracy": "Highest",
                "use": "Best accuracy",
            },
        }

        if model_name in model_info:
            info = model_info[model_name]
            print(f"  Size: {info['size']}")
            print(f"  Speed: {info['speed']}")
            print(f"  Accuracy: {info['accuracy']}")
            print(f"  Best for: {info['use']}")
        else:
            print(f"   Model: {model_name}")
            print("  Note: Model characteristics not available")

        # Show recommendations
        print("\nRecommendations:")
        if "n" in model_name:
            print("Good for: Real-time applications, edge devices")
            print("Consider: May need more training epochs for good accuracy")
        elif "s" in model_name:
            print("Good for: Mobile applications, embedded systems")
            print("Consider: Balance between speed and accuracy")
        elif "m" in model_name:
            print("Good for: General purpose training (recommended)")
            print("Consider: Best balance of speed, accuracy, and size")
        elif "l" in model_name:
            print("Good for: High accuracy requirements")
            print("Consider: Slower training and inference")
        elif "x" in model_name or "e" in model_name:
            print("Good for: Best possible accuracy")
            print("Consider: Requires more GPU memory and time")

    def _show_model_info(self, best_model_path, last_model_path, run_output_dir):
        """Shows detailed information about saved models."""
        print("\nMODEL INFORMATION:")

        # Check best model
        if os.path.exists(best_model_path):
            size_mb = os.path.getsize(best_model_path) / (1024 * 1024)
            print(f"   Best model: {best_model_path}")
            print(f"      Size: {size_mb:.1f} MB")
        else:
            print(f"   Best model not found: {best_model_path}")

        # Check last model
        if os.path.exists(last_model_path):
            size_mb = os.path.getsize(last_model_path) / (1024 * 1024)
            print(f"   Last model: {last_model_path}")
            print(f"      Size: {size_mb:.1f} MB")
        else:
            print(f"   Last model not found: {last_model_path}")

        # List all files in the run directory
        if os.path.exists(run_output_dir):
            print("\nFILES IN RESULTS FOLDER:")
            for root, _dirs, files in os.walk(run_output_dir):
                level = root.replace(run_output_dir, "").count(os.sep)
                indent = " " * 2 * level
                print(f"{indent}{os.path.basename(root)}/")
                subindent = " " * 2 * (level + 1)
                for file in files:
                    file_path = os.path.join(root, file)
                    size_mb = os.path.getsize(file_path) / (1024 * 1024)
                    print(f"{subindent}{file} ({size_mb:.1f} MB)")

        print("\nUSAGE TIPS:")
        print("Use 'best.pt' for inference (highest accuracy)")
        print("Use 'last.pt' if you want to continue training")
        print(f"All training logs and plots are in: {run_output_dir}")
        print("You can copy the model files to use in other projects")

    def _validate_existing_yaml(self, yaml_file):
        """Validate existing YAML using the same resolver as training."""
        try:
            config = self._gui_training_config()
            yaml_data = _load_yaml(yaml_file)
            names = _yaml_names_to_list(yaml_data.get("names"))
            print("YAML validation successful:")
            print(f"  Task: {config.task}")
            print(f"  Model: {config.model_name}")
            print(f"  Classes: {len(names)}")
            print(f"  Class names: {names}")
            print(f"  Train path: {config.train_path}")
            print(f"  Val path: {config.val_path}")
            return True
        except Exception as e:
            messagebox.showerror("YAML Error", f"Error reading YAML file: {str(e)}")
            return False


# --- Application Entry Point ---
def run_yolotrain_gui():
    """Entry point function."""
    print(f"Running: {pathlib.Path(__file__).name}")
    print(f"Directory: {pathlib.Path(__file__).parent.resolve()}")

    os.environ["KMP_DUPLICATE_LIB_OK"] = "TRUE"
    torch.set_num_threads(1)

    app = YOLOTrainApp()
    app.mainloop()


def build_arg_parser():
    """Build CLI parser for headless YOLO training."""
    parser = argparse.ArgumentParser(
        description="Train YOLO26/Ultralytics models from vailá getpixelvideo/SAM datasets."
    )
    parser.add_argument("--gui", action="store_true", help="Open the Tkinter GUI.")
    parser.add_argument("--data", "-d", help="Path to data.yaml.")
    parser.add_argument(
        "--task",
        choices=TASK_CHOICES,
        default="auto",
        help="YOLO task. auto reads data.yaml (kpt_shape -> pose).",
    )
    parser.add_argument(
        "--model",
        default="auto",
        help="Model name/path. auto uses YOLO26 default for the detected task.",
    )
    parser.add_argument("--epochs", type=int, help="Training epochs override.")
    parser.add_argument("--batch", type=float, help="Batch size override; -1 for Ultralytics auto.")
    parser.add_argument("--imgsz", type=int, help="Image size override.")
    parser.add_argument(
        "--device",
        help="Device override: auto, cpu, mps, 0, 0,1, etc. Defaults to YAML or auto.",
    )
    parser.add_argument("--project", help="Output project directory. Default: <dataset>/runs.")
    parser.add_argument("--name", default="yolo_training", help="Run name under project directory.")
    parser.add_argument(
        "--exist-ok",
        action="store_true",
        default=True,
        help="Allow overwriting/reusing project/name (default).",
    )
    parser.add_argument(
        "--dry-run",
        action="store_true",
        help="Validate YAML and print resolved config without downloading/training.",
    )
    parser.add_argument(
        "--arg",
        action="append",
        default=[],
        metavar="KEY=VALUE",
        help="Extra Ultralytics train override. May be repeated, e.g. --arg workers=4.",
    )
    return parser


def main(argv=None):
    """CLI entry point. No args opens the GUI for backwards compatibility."""
    parser = build_arg_parser()
    args = parser.parse_args(argv)
    if args.gui or not args.data:
        run_yolotrain_gui()
        return 0

    try:
        extra_args = _parse_extra_train_args(args.arg)
        config = train_yolo_dataset(
            args.data,
            task=args.task,
            model=args.model,
            epochs=args.epochs,
            batch=args.batch,
            imgsz=args.imgsz,
            device=args.device,
            project=args.project,
            name=args.name,
            exist_ok=args.exist_ok,
            dry_run=args.dry_run,
            extra_train_args=extra_args,
        )
    except Exception as exc:
        print(f"ERROR: {exc}", file=sys.stderr)
        return 1
    if args.dry_run:
        print("Resolved YOLO training config:")
        print(f"  data: {config.yaml_file}")
        print(f"  dataset: {config.dataset_dir}")
        print(f"  task: {config.task}")
        print(f"  model: {config.model_name}")
        print(f"  train: {config.train_path} ({_image_count(config.train_path)} images)")
        print(f"  val: {config.val_path} ({_image_count(config.val_path)} images)")
        print(f"  epochs: {config.epochs}")
        print(f"  batch: {config.batch}")
        print(f"  imgsz: {config.imgsz}")
        print(f"  device: {config.device}")
        print(f"  project: {config.project}")
        print(f"  name: {config.name}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
